random_state: 42
export_data: False
generate_meta_data: False
generate_time_series_plots: False
generate_histogram_plots:
  run: False
  number_of_bins: 30
generate_custom_plots: False

data:
  timestamp: 'DATE'

  identify_missing_data:
    run: False
    unique_values:
      run: True
      threshold: 5
    explicit_missing_values:
      run: True
      indicators: ['NA', 'na', 'nan', 'NAN', 'NaN', 'null', 'NULL', 'None', 'none', -999, -9999, '?']
    repeating_values:
      run: True
      threshold: 18
      proportion_threshold: 0.5

  identify_outliers:
    run: True
    method: 'iqr'
    iqr_threshold: 4
    z_score_threshold: 3
    mad_threshold: 3
    dbscan_eps: 0.5
    dbscan_min_samples: 5
    isolation_forest_threshold: 0.001
    lof_threshold: 0.001

  identify_shutdowns:
    run: False
    shutdown_features:
      - 'EMPTY_FEATURE'
    cutoff_values:
      - 10000

  correct_missing_data:
    run: True
    interpolate_time_series:
      run: True
      method: 'bfill'
      limit_direction: 'both'
      max_gap: 6
    interpolate_highly_regular_time_series:
      run: True
      method: 'bfill'
      limit_direction: 'both'
      regular_interval_min: 24
    replace_missing_values_with_x:
      run: False
      x: 0
    replace_missing_values_with_last_known_value:
      run: False
      backfill: False
    delete_all_rows_with_missing_values:
      run: False

  introduce_lags:
    run: False
    features: ['FAKE_FEATURE']
    lags: [1]
    optimise_lags: True
    target: 'FAKE_FEATURE'
    max_lag: 144
    overwrite_existing_features: True

  rolling_aggregation:
    aggregation_types:
      - 'mean'
    window: 24
    min_periods: 24
    window_selection_frequency: 1

  feature_engineering:
    run: True

  correct_missing_data_after_aggregation:
    run: True
    interpolate_time_series:
      run: True
      method: 'bfill'
      limit_direction: 'both'
      max_gap: 6
    interpolate_highly_regular_time_series:
      run: False
      method: 'bfill'
      limit_direction: 'both'
      regular_interval_min: 24
    replace_missing_values_with_x:
      run: True
      x: 0
    replace_missing_values_with_last_known_value:
      run: True
      backfill: True
    delete_all_rows_with_missing_values:
      run: True

  filter_shutdowns:
    run: True

iron_concentrate_perc:
  model:
    target: 'IRON_CONCENTRATE_PERC_mean'
    feed_blend_training_features:
      - 'IRON_FEED_PERC_mean'
      - 'SILICA_FEED_PERC_mean'
      - 'STARCH_FLOW_mean'
      - 'AMINA_FLOW_mean'
      - 'ORE_PULP_FLOW_mean'
      - 'ORE_PULP_PH_mean'
      - 'ORE_PULP_DENSITY_mean'
    training_features:
      - 'IRON_FEED_PERC_mean'
      - 'SILICA_FEED_PERC_mean'
      - 'STARCH_FLOW_mean'
      - 'AMINA_FLOW_mean'
      - 'ORE_PULP_FLOW_mean'
      - 'ORE_PULP_PH_mean'
      - 'ORE_PULP_DENSITY_mean'
      - 'FLOTATION_COLUMN_01_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_02_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_03_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_04_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_05_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_06_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_07_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_01_LEVEL_mean'
      - 'FLOTATION_COLUMN_02_LEVEL_mean'
      - 'FLOTATION_COLUMN_03_LEVEL_mean'
      - 'FLOTATION_COLUMN_04_LEVEL_mean'
      - 'FLOTATION_COLUMN_05_LEVEL_mean'
      - 'FLOTATION_COLUMN_06_LEVEL_mean'
      - 'FLOTATION_COLUMN_07_LEVEL_mean'
    model_choice: 'gbm'
    random_state: 42
    number_of_models: 1
    model_name: 'iron_concentrate_perc'
    metric: 'rmse'
    generate_feature_importance: True

    hyperparameters:
      learning_rate: 
        - 0.1
      max_depth:
        - 3
      min_samples_leaf:
        - 1
      max_iter:
        - 100
      max_leaf_nodes:
        - 31
      l2_regularization:
        - 0.0
      max_bins:
        - 255
      monotonic_cst:
        - [0,0,0,0,0, 0,0,0,0,0, 0,0,0,0,0, 0,0,0,0,0, 0]

    univariable_feature_importance:
      run: True
      method: 'kendall'

    feature_selection:
      run: False
      filter_low_variance:
        run: True
        threshold: 0.01
      filter_univariable_feature_importance:
        run: True
        method: 'kendall'
        threshold: 0.05
      filter_feature_importance:
        run: False
        threshold: 1

    correlation_matrix:
      run: True
      method: 'kendall'

  partial_plots:
    plot_confidence_interval: True
    plot_feature_density: True
    plot_feature_density_as_histogram: False
    number_of_bins_in_histogram: 10
    grid_resolution: 200

silica_concentrate_perc:
  model:
    target: 'SILICA_CONCENTRATE_PERC_mean'
    feed_blend_training_features:
      - 'IRON_FEED_PERC_mean'
      - 'SILICA_FEED_PERC_mean'
      - 'STARCH_FLOW_mean'
      - 'AMINA_FLOW_mean'
      - 'ORE_PULP_FLOW_mean'
      - 'ORE_PULP_PH_mean'
      - 'ORE_PULP_DENSITY_mean'
    training_features:
      - 'IRON_FEED_PERC_mean'
      - 'SILICA_FEED_PERC_mean'
      - 'STARCH_FLOW_mean'
      - 'AMINA_FLOW_mean'
      - 'ORE_PULP_FLOW_mean'
      - 'ORE_PULP_PH_mean'
      - 'ORE_PULP_DENSITY_mean'
      - 'FLOTATION_COLUMN_01_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_02_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_03_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_04_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_05_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_06_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_07_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_01_LEVEL_mean'
      - 'FLOTATION_COLUMN_02_LEVEL_mean'
      - 'FLOTATION_COLUMN_03_LEVEL_mean'
      - 'FLOTATION_COLUMN_04_LEVEL_mean'
      - 'FLOTATION_COLUMN_05_LEVEL_mean'
      - 'FLOTATION_COLUMN_06_LEVEL_mean'
      - 'FLOTATION_COLUMN_07_LEVEL_mean'
    model_choice: 'gbm'
    random_state: 42
    number_of_models: 1
    model_name: 'silica_concentrate_perc'
    metric: 'rmse'
    generate_feature_importance: True

    hyperparameters:
      learning_rate: 
        - 0.1
      max_depth:
        - 3
      min_samples_leaf:
        - 1
      max_iter:
        - 100
      max_leaf_nodes:
        - 31
      l2_regularization:
        - 0.0
      max_bins:
        - 255
      monotonic_cst:
        - [0,0,0,0,0, 0,0,0,0,0, 0,0,0,0,0, 0,0,0,0,0, 0]

    univariable_feature_importance:
      run: True
      method: 'kendall'

    feature_selection:
      run: False
      filter_low_variance:
        run: True
        threshold: 0.01
      filter_univariable_feature_importance:
        run: True
        method: 'kendall'
        threshold: 0.05
      filter_feature_importance:
        run: False
        threshold: 1

    correlation_matrix:
      run: True
      method: 'kendall'

  partial_plots:
    plot_confidence_interval: True
    plot_feature_density: True
    plot_feature_density_as_histogram: False
    number_of_bins_in_histogram: 10
    grid_resolution: 200

clustering:
  feed_blend_model:
    run: True
    training_features:
      - 'IRON_FEED_PERC_mean'
      - 'SILICA_FEED_PERC_mean'
      - 'STARCH_FLOW_mean'
      - 'AMINA_FLOW_mean'
      - 'ORE_PULP_FLOW_mean'
      - 'ORE_PULP_PH_mean'
      - 'ORE_PULP_DENSITY_mean'
    informational_features:
      - 'FLOTATION_COLUMN_01_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_02_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_03_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_04_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_05_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_06_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_07_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_01_LEVEL_mean'
      - 'FLOTATION_COLUMN_02_LEVEL_mean'
      - 'FLOTATION_COLUMN_03_LEVEL_mean'
      - 'FLOTATION_COLUMN_04_LEVEL_mean'
      - 'FLOTATION_COLUMN_05_LEVEL_mean'
      - 'FLOTATION_COLUMN_06_LEVEL_mean'
      - 'FLOTATION_COLUMN_07_LEVEL_mean'
      - 'IRON_CONCENTRATE_PERC_mean'
      - 'SILICA_CONCENTRATE_PERC_mean'
    include_row_count_sum: True
    model_choice: 'kmeans'
    k_means_n_clusters: 10
    k_means_max_iter: 300
    dbscan_eps: 0.5
    dbscan_min_samples: 5
    agglomerative_n_clusters: 3
    random_state: 42
    
  controllables_model:
    run: True
    training_features:
      - 'FLOTATION_COLUMN_01_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_02_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_03_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_04_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_05_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_06_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_07_AIR_FLOW_mean'
      - 'FLOTATION_COLUMN_01_LEVEL_mean'
      - 'FLOTATION_COLUMN_02_LEVEL_mean'
      - 'FLOTATION_COLUMN_03_LEVEL_mean'
      - 'FLOTATION_COLUMN_04_LEVEL_mean'
      - 'FLOTATION_COLUMN_05_LEVEL_mean'
      - 'FLOTATION_COLUMN_06_LEVEL_mean'
      - 'FLOTATION_COLUMN_07_LEVEL_mean'
    informational_features:
      - 'IRON_FEED_PERC_mean'
      - 'SILICA_FEED_PERC_mean'
      - 'STARCH_FLOW_mean'
      - 'AMINA_FLOW_mean'
      - 'ORE_PULP_FLOW_mean'
      - 'ORE_PULP_PH_mean'
      - 'ORE_PULP_DENSITY_mean'
      - 'IRON_CONCENTRATE_PERC_mean'
      - 'SILICA_CONCENTRATE_PERC_mean'
    include_row_count_sum: True
    model_choice: 'kmeans'
    k_means_n_clusters: 10
    k_means_max_iter: 300
    dbscan_eps: 0.5
    dbscan_min_samples: 5
    agglomerative_n_clusters: 3
    random_state: 42

simulation:
  feed_blend_model:
    confidence_interval: False
    feature_values_to_simulate: null
  feed_blend_and_controllables_model:
    confidence_interval: False
    feature_values_to_simulate: null

optimisation:
  feature_to_optimise: 'IRON_CONCENTRATE_PERC_mean'
  direction_to_optimise: 'maximise'
  constraints:
    features: ['SILICA_CONCENTRATE_PERC_mean']
    limits: [[0,100]]
