feature_to_optimise: 'IRON_AND_SILICA_CONCENTRATE_PERC_mean' #'IRON_CONCENTRATE_PERC_mean'
direction_to_optimise: 'maximise'
constraints:
  features: ['SILICA_CONCENTRATE_PERC_mean']
  limits: [[0,100]]